### ISSUE TITLE
请问：作者是否有 Taro 3.0 的适配计划

### ISSUE THREAD

**Issue by qq189958718** [redux-model/redux-model#7]
redux-model 的类型提示太棒了，我们非常喜欢 redux-model，目前也有几个 ts 项目在用。

最近 taro 升级到了 3.0，`"@redux-model/taro": "^6.9.2",` 与 `"@tarojs/taro": "3.0.2",` 一起使用会报错：

```
MiniProgramError
Object prototype may only be an Object or null: undefined
TypeError: Object prototype may only be an Object or null: undefined
    at setPrototypeOf (<anonymous>)
    at Module.__extends (http://127.0.0.1:55794/appservice/app.js:30282:5)
    at http://127.0.0.1:55794/appservice/app.js:2438:11
    at Object../node_modules/@redux-model/taro/libs/PersistGate.js (http://127.0.0.1:55794/appservice/app.js:2470:2)
    at __webpack_require__ (http://127.0.0.1:55794/appservice/runtime.js:81:30)
    at Object../node_modules/@redux-model/taro/libs/index.js (http://127.0.0.1:55794/appservice/app.js:2563:21)
    at __webpack_require__ (http://127.0.0.1:55794/appservice/runtime.js:81:30)
    at Object../src/store/index.ts (http://127.0.0.1:55794/appservice/app.js:30566:75)
    at __webpack_require__ (http://127.0.0.1:55794/appservice/runtime.js:81:30)
    at Object../node_modules/@tarojs/mini-runner/node_modules/babel-loader/lib/index.js!./src/app.tsx (http://127.0.0.1:55794/appservice/app.js:3501:64)
```

希望作者可以看一下这个问题

**Comment by fwh1990** [comment]
Hello，感谢使用这个框架。最近正在重构整个项目。taro3.0是个大改，原 @tarojs/redux 也是不再需要了。敬请期待

**Comment by fwh1990** [comment]
争取下周全部弄好

**Comment by fwh1990** [comment]
Hello，已经发布beta版本 ，可以安装 `@redux-model/taro@next`试用。这几天都在更新和查找bug，欢迎随时提意见建议

**Comment by qq189958718** [comment]
Hi，Taro 小程序已经可以正常跑起来了，但编译成 h5 请求接口的时候还有点问题

当前环境

```
👽 Taro v3.0.3


  Taro CLI 3.0.3 environment info:
    System:
      OS: macOS 10.15.5
      Shell: 5.7.1 - /bin/zsh
    Binaries:
      Node: 12.16.1 - ~/.nvm/versions/node/v12.16.1/bin/node
      Yarn: 1.22.4 - ~/.nvm/versions/node/v12.16.1/bin/yarn
      npm: 6.13.4 - ~/.nvm/versions/node/v12.16.1/bin/npm
    npmPackages:
      @tarojs/components: 3.0.3 => 3.0.3 
      @tarojs/mini-runner: 3.0.3 => 3.0.3 
      @tarojs/react: 3.0.3 => 3.0.3 
      @tarojs/runtime: 3.0.3 => 3.0.3 
      @tarojs/taro: 3.0.3 => 3.0.3 
      @tarojs/webpack-runner: 3.0.3 => 3.0.3 
      babel-preset-taro: 3.0.3 => 3.0.3 
      eslint-config-taro: 3.0.3 => 3.0.3 
      react: ^16.10.0 => 16.13.1 
```

以下是报错信息

```
Uncaught TypeError: taro_1.default.request is not a function
    at HttpService.runAction (HttpService.js?809a:47)
    at eval (BaseHttpService.js?169a:121)
    at eval (BaseHttpService.js?169a:80)
    at Object.eval [as dispatch] (DynamicMiddleware.js?3c0f:14)
    at StoreHelper.dispatch (StoreHelper.js?9ea7:69)
    at User.eval [as queryCodeList] (BaseRequestAction.js?cd52:120)
    at eval (index.tsx?195d:10)
    at commitHookEffectListMount (react-dom.development.js?61bb:19731)
    at commitPassiveHookEffects (react-dom.development.js?61bb:19769)
    at HTMLUnknownElement.callCallback (react-dom.development.js?61bb:188)
```

**Comment by fwh1990** [comment]
> ，但编译成 h5 请求接口的时候还有点问题

已经处理，属于taro老问题了，以为taro@3.0会修复

**Comment by fwh1990** [comment]
这次加了挺多新功能，文档这几天完善一下

**Comment by fwh1990** [comment]
你好，7.0已经正式发布，感谢使用。有任何问题欢迎反馈

**Comment by fwh1990** [comment]
文档已经完善，建议您看看，一些新功能之类的。觉得好用帮忙推广一下，没有大厂光环太难了。再次感谢
